In [54]:
import os
os.getcwd()

'c:\\Users\\marcelo\\AppData\\Local\\Programs\\Microsoft VS Code'

# EXEMPLO 1 - IDADES

Abaixo criamos um dataframe que contem uma coluna de idade, propositalmente colocamos dados que indicam problemas de digitação (ex, numeros altos).

Como resiltresultado, vemos uma idades bem alta. Imagine apresentar para o gestoroui ao demandante da análise que a "média da idade dos clietes é 136,78 anos". Isso logo demosntra a falta de atençao, pois tem algo errado com este número!

In [ ]:
%pip install seaborn

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

In [31]:
# Criando um Dataframe com algumas idades para exemplo
dados = {'Idade': [23, 45, 35, 400, 45, 35, 233, 345, 70]
}

df = pd.DataFrame(dados)
print(df)

   Idade
0     23
1     45
2     35
3    400
4     45
5     35
6    233
7    345
8     70

In [32]:
# Neste caso, o o pandas retorna este tipo de saída ao invés de float "puro" do pytthon.
df['Idade'].mean()

np.float64(136.77777777777777)

In [33]:
# Confertaendo para float comum.
float(df['Idade'].mean())

136.77777777777777

In [34]:
# Arredondando para 2 casas decimais.
round(float(df['Idade'].mean()), 2)

136.78

# EXEMPLO 2 - CIDADE

Outros problemas que costuma ser frequente na qualidade dos dados:
- Acentuação
- Erros de Digitação
- Letras Maiúsculas e Minúsculas

In [35]:
dados = {
    'Idade': [ 25, 35, 45, 400, 55, 544, 60, 234, 12],
    'Cidade': [ 'São Paulo', 'Salvador', 'Rio de Janeiro', 'Curitiba', 'Salvador', 'Sao Paulo', 'salvador', 'Curitiba', 'Rio de Janeiro']
}
df = pd.DataFrame(dados)
print(df)

   Idade          Cidade
0     25       São Paulo
1     35        Salvador
2     45  Rio de Janeiro
3    400        Curitiba
4     55        Salvador
5    544       Sao Paulo
6     60        salvador
7    234        Curitiba
8     12  Rio de Janeiro

Vamos trazer a média das idades por cidade realizando um agrupamento pod cidades como vimos no módulo de etatística básica.

In [37]:
df.groupby('Cidade')['Idade'].mean().reset_index()

           Cidade  Idade
0        Curitiba  317.0
1  Rio de Janeiro   28.5
2        Salvador   45.0
3       Sao Paulo  544.0
4       São Paulo   25.0
5        salvador   60.0

Neste exemplo, notamos que as ciades que deveriam estar agrupadas acabam se repetindo e alguns erros de digotação e padronização dos nomes.
Se não realizarmos o tratamento desses dados dificilmente chegaremos a média correta das idades por cidade.

# EXEMPO 3 - SALÁRIO

Muitas vezes também acabamos lidando com  valores ausentes nas nosas bases de dados. Isso acontece pois muitos clientes acabam não fornecendo todos seus daos ou até mesmo por conta de falhas na coleta de dados.

In [44]:
dados = {
    'Idade': [25, 45, 30, 35, 400, 50, 544, 60, 65, 24, 233, 70, 36],
    'Cidade': ['São Paulo', 'Salvador', 'Rio de Janeiro', 'Curitiba', 'Salvador', 'Sao Paulo', 'salvador', 'Curitiba', 'Rio de Janeiro', 'São Paulo', 'Salvador', 'Rio de Janeiro', 'Curitiba'],
    'Salario': ['1200,0', '0', '4000,0', '500,0','0','0','0', '0','3000,0', '2500,0','0','0','1600,0'] 
}

df = pd.DataFrame(dados)
print(df)

    Idade          Cidade Salario
0      25       São Paulo  1200,0
1      45        Salvador       0
2      30  Rio de Janeiro  4000,0
3      35        Curitiba   500,0
4     400        Salvador       0
5      50       Sao Paulo       0
6     544        salvador       0
7      60        Curitiba       0
8      65  Rio de Janeiro  3000,0
9      24       São Paulo  2500,0
10    233        Salvador       0
11     70  Rio de Janeiro       0
12     36        Curitiba  1600,0

Neste outro exemplo, o dataframe acima, algumas linhas estáo sem preenchimentos dos dados de sálario, retornando 0. EM uma primeira podemos até pensar quepor ter outras linhas preenciidas os valores faltantes podem não afetar sua analise.
Mas notem que algumas cidades como Salvador não tem valores de salário. Como sabemos alguns modelos de machine learning de aprendizado supervisionado utilizam daos históricos para aprender com esses dados. Imaginem que nosso modelo tivesse a proposta de prever exatamente o salário apenas analisando a idade e cidade?. Neste casso se o modelo não tiver exemplos para a cidade de Salvador isso pode enviezar os resultados sempre que essa cidade aparecer. O modelo trará uma conclusão distorcida de que sempre nessa ciade o salário será 0.
Outro fator é que quanto mais dados ausentes, masi dificultosa será a aprendizagem do modelo. O modelo precisa do máximo de informação possível.

MÓDULO 14 - AULA 2
Verificando e Tratando tipos de dados

Neste módulo, aplicaremos o primeiro modelo machine learning, tentando identificar qiasi são os clientes propensos aso Churn.

CHURN é um termo utilizado em empresa spara descrever a taxa de perda ou cancelamento de cliente ao longo do tempo.

(para saber mais sobre o churn -> https://contentsquare.com/guides/customer-retention/ )

In [56]:
try:
	os  # noqa: F821
except NameError:
	import os

file_path = "CHURN_CREDIT_MOD14.csv"
if os.path.exists(file_path):
	df = pd.read_csv(file_path, delimiter=';')
else:
	print(f"Arquivo {file_path!r} não encontrado em {os.getcwd()}. Usando dataframe vazio como placeholder.")
	df = pd.DataFrame()

df.head(10)

Arquivo 'CHURN_CREDIT_MOD14.csv' não encontrado em c:\Users\marcelo\AppData\Local\Programs\Microsoft VS Code. Usando dataframe vazio como placeholder.

Empty DataFrame
Columns: []
Index: []